export interface AnalyzeApiResponse {
  Kecamatan: string;
  Kabupaten_Kota: string;
  url_gambar: string;
  latitude: number;
  longitude: number;
  industri_terdekat: string;
  tipe_industri: string;
  jarak_industri_km: number;
  kategori_dampak_industri: string;
  industri_terdekat_2: string;
  tipe_industri_2: string;
  jarak_industri_2_km: number;
  industri_terdekat_3: string;
  tipe_industri_3: string;
  jarak_industri_3_km: number;
  penjelasan_kualitas: string;
  slug: string;
  industri_relevan_terdekat: string;
  tipe_industri_relevan: string;
  jarak_industri_relevan_km: number;
  relevansi_industri: number;
  jumlah_industri_radius_10km: number;
  kepadatan_industri: number;
  total_relevansi_radius: number;
  daftar_industri_radius: string[];
  indeks_dampak_industri: number;
  kepadatan_penduduk_kecamatan: number;
  indeks_pengaruh_urban: number;
  Pantai: string;
  pantai: string;
  geojson: unknown | null;
}
