import type { Metadata } from "next";
import { Suspense } from "react";
import {
  getLeaderboardSummary,
  getTopBeaches,
  getAllBeaches,
  getUniqueLocations,
  getScoreDistribution,
} from "@/services/leaderboard.service";
import { LeaderboardClient } from "@/components/main/leaderboard/leaderboard-client";
import { LeaderboardLoading } from "@/components/main/leaderboard/leaderboard-loading";

export const metadata: Metadata = {
  title: "Beach Leaderboard | AQuality",
  description:
    "Compare coastal water quality rankings generated by AI analysis. View environmental scores, pollution levels, and water clarity for beaches.",
};

async function LeaderboardContent() {
  const [allBeaches, summary, topBeaches, locations, distribution] =
    await Promise.all([
      getAllBeaches(),
      getLeaderboardSummary(),
      getTopBeaches(3),
      getUniqueLocations(),
      getScoreDistribution(),
    ]);

  return (
    <LeaderboardClient
      initialData={allBeaches}
      initialSummary={summary}
      initialTopBeaches={topBeaches}
      initialLocations={locations}
      initialDistribution={distribution}
    />
  );
}

export default function LeaderboardPage() {
  return (
    <Suspense fallback={<LeaderboardLoading />}>
      <LeaderboardContent />
    </Suspense>
  );
}
