import { Button } from "@/components/ui/button";
import { Download, RefreshCw, Trophy } from "lucide-react";

interface LeaderboardHeaderProps {
  onRefresh?: () => void;
  isRefreshing?: boolean;
}

export function LeaderboardHeader({
  onRefresh,
  isRefreshing,
}: LeaderboardHeaderProps) {
  return (
    <section
      id="leaderboard-hero"
      className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"
    >
      <div className="space-y-1.5">
        <div className="flex items-center gap-2.5">
          <div className="flex size-9 items-center justify-center rounded-lg bg-primary/10 text-primary">
            <Trophy className="size-5" />
          </div>
          <h1 className="text-2xl font-bold tracking-tight">
            Beach Leaderboard
          </h1>
        </div>
        <p className="text-sm text-muted-foreground">
          Compare coastal water quality rankings generated by AI analysis.
        </p>
      </div>

      <div className="flex items-center gap-2">
        <Button variant="outline" size="sm" id="export-report-btn">
          <Download className="size-3.5" data-icon="inline-start" />
          Export Report
        </Button>
        <Button
          variant="outline"
          size="sm"
          onClick={onRefresh}
          disabled={isRefreshing}
          id="refresh-data-btn"
        >
          <RefreshCw
            className={`size-3.5 ${isRefreshing ? "animate-spin" : ""}`}
            data-icon="inline-start"
          />
          Refresh
        </Button>
      </div>
    </section>
  );
}
